# Site settings
title: Nguyễn Văn Lắm
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nguyễn Văn Lắm
user_description: Fresher Developer, Được đào tạo ở CyberSoft Academy
user_title: Web Devloper
email: vanlam1412@gmail.com
# twitter_username: lorem_ipsum
linkedin_username: nguyen-van-lam-2449441aa
github_username: vanlam2001
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]
